// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNjzr3UMwiqXEVT8guIEAoD_Fiw0L2IfI',
    appId: '1:377379230312:web:485b881a3be1a92c8121dd',
    messagingSenderId: '377379230312',
    projectId: 'tu-dien-han-nom-58836',
    authDomain: 'tu-dien-han-nom-58836.firebaseapp.com',
    storageBucket: 'tu-dien-han-nom-58836.firebasestorage.app',
    measurementId: 'G-LRJ1XRR4T5',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2yH8v2qkjddUU8rG82Av4eaab9RRt6WA',
    appId: '1:377379230312:ios:775f3db74933d3aa8121dd',
    messagingSenderId: '377379230312',
    projectId: 'tu-dien-han-nom-58836',
    storageBucket: 'tu-dien-han-nom-58836.firebasestorage.app',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2yH8v2qkjddUU8rG82Av4eaab9RRt6WA',
    appId: '1:377379230312:ios:775f3db74933d3aa8121dd',
    messagingSenderId: '377379230312',
    projectId: 'tu-dien-han-nom-58836',
    storageBucket: 'tu-dien-han-nom-58836.firebasestorage.app',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNjzr3UMwiqXEVT8guIEAoD_Fiw0L2IfI',
    appId: '1:377379230312:web:ec13b3b8b691b34f8121dd',
    messagingSenderId: '377379230312',
    projectId: 'tu-dien-han-nom-58836',
    authDomain: 'tu-dien-han-nom-58836.firebaseapp.com',
    storageBucket: 'tu-dien-han-nom-58836.firebasestorage.app',
    measurementId: 'G-DK0T6V741F',
  );
}
